[package]
name = "sim-em-simple"
version = "0.1.0"
authors = [ "Alexi Chepura <a.chepura@gmail.com>" ]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
resolver = "2"

[dependencies]
bevy = { version = "0.18", features = [
    "bevy_camera_controller",
    "free_camera",
    "bevy_core_pipeline"
]}
nalgebra = "0.33"
parry3d = "0.21"
